package com.furnaghan.exif.tag;

import com.furnaghan.exif.ExifTagReference;
import com.furnaghan.exif.ImageFileDirectory;
import com.furnaghan.exif.io.FieldType;
import com.google.common.base.Supplier;

public enum Image implements Supplier<ExifTagReference> {
	ProcessingSoftware( 0x000b, FieldType.Ascii ), // The name and version of the software used to post-process the picture.
	NewSubfileType( 0x00fe, FieldType.Long ), // A general indication of the kind of data contained in this subfile.
	SubfileType( 0x00ff, FieldType.Short ), // A general indication of the kind of data contained in this subfile. This field is deprecated. The NewSubfileType field should be used instead.
	ImageWidth( 0x0100, FieldType.Long ), // The number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag.
	ImageLength( 0x0101, FieldType.Long ), // The number of rows of image data. In JPEG compressed data a JPEG marker is used instead of this tag.
	BitsPerSample( 0x0102, FieldType.Short ), // The number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also &lt;SamplesPerPixel&gt;. In JPEG compressed data a JPEG marker is used instead of this tag.
	Compression( 0x0103, FieldType.Short ), // The compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6.
	PhotometricInterpretation( 0x0106, FieldType.Short ), // The pixel composition. In JPEG compressed data a JPEG marker is used instead of this tag.
	Thresholding( 0x0107, FieldType.Short ), // For black and white TIFF files that represent shades of gray, the technique used to convert from gray to black and white pixels.
	CellWidth( 0x0108, FieldType.Short ), // The width of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.
	CellLength( 0x0109, FieldType.Short ), // The length of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.
	FillOrder( 0x010a, FieldType.Short ), // The logical order of bits within a byte
	DocumentName( 0x010d, FieldType.Ascii ), // The name of the document from which this image was scanned
	ImageDescription( 0x010e, FieldType.Ascii ), // A character string giving the title of the image. It may be a comment such as &#34;1988 company picnic&#34; or the like. Two-bytes character codes cannot be used. When a 2-bytes code is necessary, the Exif Private tag &lt;UserComment&gt; is to be used.
	Make( 0x010f, FieldType.Ascii ), // The manufacturer of the recording equipment. This is the manufacturer of the DSC, scanner, video digitizer or other equipment that generated the image. When the field is left blank, it is treated as unknown.
	Model( 0x0110, FieldType.Ascii ), // The model name or model number of the equipment. This is the model name or number of the DSC, scanner, video digitizer or other equipment that generated the image. When the field is left blank, it is treated as unknown.
	StripOffsets( 0x0111, FieldType.Long ), // For each strip, the byte offset of that strip. It is recommended that this be selected so the number of strip bytes does not exceed 64 Kbytes. With JPEG compressed data this designation is not needed and is omitted. See also &lt;RowsPerStrip&gt; and &lt;StripByteCounts&gt;.
	Orientation( 0x0112, FieldType.Short ), // The image orientation viewed in terms of rows and columns.
	SamplesPerPixel( 0x0115, FieldType.Short ), // The number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag.
	RowsPerStrip( 0x0116, FieldType.Long ), // The number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted. See also &lt;StripOffsets&gt; and &lt;StripByteCounts&gt;.
	StripByteCounts( 0x0117, FieldType.Long ), // The total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted.
	XResolution( 0x011a, FieldType.Rational ), // The number of pixels per &lt;ResolutionUnit&gt; in the &lt;ImageWidth&gt; direction. When the image resolution is unknown, 72 [dpi] is designated.
	YResolution( 0x011b, FieldType.Rational ), // The number of pixels per &lt;ResolutionUnit&gt; in the &lt;ImageLength&gt; direction. The same value as &lt;XResolution&gt; is designated.
	PlanarConfiguration( 0x011c, FieldType.Short ), // Indicates whether pixel components are recorded in a chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed.
	GrayResponseUnit( 0x0122, FieldType.Short ), // The precision of the information contained in the GrayResponseCurve.
	GrayResponseCurve( 0x0123, FieldType.Short ), // For grayscale data, the optical density of each possible pixel value.
	T4Options( 0x0124, FieldType.Long ), // T.4-encoding options.
	T6Options( 0x0125, FieldType.Long ), // T.6-encoding options.
	ResolutionUnit( 0x0128, FieldType.Short ), // The unit for measuring &lt;XResolution&gt; and &lt;YResolution&gt;. The same unit is used for both &lt;XResolution&gt; and &lt;YResolution&gt;. If the image resolution is unknown, 2 (inches) is designated.
	PageNumber( 0x0129, FieldType.Short ), // The page number of the page from which this image was scanned.
	TransferFunction( 0x012d, FieldType.Short ), // A transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (&lt;ColorSpace&gt;).
	Software( 0x0131, FieldType.Ascii ), // This tag records the name and version of the software or firmware of the camera or image input device used to generate the image. The detailed format is not specified, but it is recommended that the example shown below be followed. When the field is left blank, it is treated as unknown.
	DateTime( 0x0132, FieldType.Ascii ), // The date and time of image creation. In Exif standard, it is the date and time the file was changed.
	Artist( 0x013b, FieldType.Ascii ), // This tag records the name of the camera owner, photographer or image creator. The detailed format is not specified, but it is recommended that the information be written as in the example below for ease of Interoperability. When the field is left blank, it is treated as unknown. Ex.) &#34;Camera owner, John Smith; Photographer, Michael Brown; Image creator, Ken James&#34;
	HostComputer( 0x013c, FieldType.Ascii ), // This tag records information about the host computer used to generate the image.
	Predictor( 0x013d, FieldType.Short ), // A predictor is a mathematical operator that is applied to the image data before an encoding scheme is applied.
	WhitePoint( 0x013e, FieldType.Rational ), // The chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the colorspace information tag (&lt;ColorSpace&gt;).
	PrimaryChromaticities( 0x013f, FieldType.Rational ), // The chromaticity of the three primary colors of the image. Normally this tag is not necessary, since colorspace is specified in the colorspace information tag (&lt;ColorSpace&gt;).
	ColorMap( 0x0140, FieldType.Short ), // A color map for palette color images. This field defines a Red-Green-Blue color map (often called a lookup table) for palette-color images. In a palette-color image, a pixel value is used to index into an RGB lookup table.
	HalftoneHints( 0x0141, FieldType.Short ), // The purpose of the HalftoneHints field is to convey to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail.
	TileWidth( 0x0142, FieldType.Short ), // The tile width in pixels. This is the number of columns in each tile.
	TileLength( 0x0143, FieldType.Short ), // The tile length (height) in pixels. This is the number of rows in each tile.
	TileOffsets( 0x0144, FieldType.Short ), // For each tile, the byte offset of that tile, as compressed and stored on disk. The offset is specified with respect to the beginning of the TIFF file. Note that this implies that each tile has a location independent of the locations of other tiles.
	TileByteCounts( 0x0145, FieldType.Short ), // For each tile, the number of (compressed) bytes in that tile. See TileOffsets for a description of how the byte counts are ordered.
	SubIFDs( 0x014a, FieldType.Long ), // Defined by Adobe Corporation to enable TIFF Trees within a TIFF file.
	InkSet( 0x014c, FieldType.Short ), // The set of inks used in a separated (PhotometricInterpretation=5) image.
	InkNames( 0x014d, FieldType.Ascii ), // The name of each ink used in a separated (PhotometricInterpretation=5) image.
	NumberOfInks( 0x014e, FieldType.Short ), // The number of inks. Usually equal to SamplesPerPixel, unless there are extra samples.
	DotRange( 0x0150, FieldType.Byte ), // The component values that correspond to a 0% dot and 100% dot.
	TargetPrinter( 0x0151, FieldType.Ascii ), // A description of the printing environment for which this separation is intended.
	ExtraSamples( 0x0152, FieldType.Short ), // Specifies that each pixel has m extra components whose interpretation is defined by one of the values listed below.
	SampleFormat( 0x0153, FieldType.Short ), // This field specifies how to interpret each data sample in a pixel.
	SMinSampleValue( 0x0154, FieldType.Short ), // This field specifies the minimum sample value.
	SMaxSampleValue( 0x0155, FieldType.Short ), // This field specifies the maximum sample value.
	TransferRange( 0x0156, FieldType.Short ), // Expands the range of the TransferFunction
	ClipPath( 0x0157, FieldType.Byte ), // A TIFF ClipPath is intended to mirror the essentials of PostScript&#39;s path creation functionality.
	XClipPathUnits( 0x0158, FieldType.SShort ), // The number of units that span the width of the image, in terms of integer ClipPath coordinates.
	YClipPathUnits( 0x0159, FieldType.SShort ), // The number of units that span the height of the image, in terms of integer ClipPath coordinates.
	Indexed( 0x015a, FieldType.Short ), // Indexed images are images where the &#39;pixels&#39; do not represent color values, but rather an index (usually 8-bit) into a separate color table, the ColorMap.
	JPEGTables( 0x015b, FieldType.Undefined ), // This optional tag may be used to encode the JPEG quantization and Huffman tables for subsequent use by the JPEG decompression process.
	OPIProxy( 0x015f, FieldType.Short ), // OPIProxy gives information concerning whether this image is a low-resolution proxy of a high-resolution image (Adobe OPI).
	JPEGProc( 0x0200, FieldType.Long ), // This field indicates the process used to produce the compressed data
	JPEGInterchangeFormat( 0x0201, FieldType.Long ), // The offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data.
	JPEGInterchangeFormatLength( 0x0202, FieldType.Long ), // The number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data. JPEG thumbnails are not divided but are recorded as a continuous JPEG bitstream from SOI to EOI. Appn and COM markers should not be recorded. Compressed thumbnails must be recorded in no more than 64 Kbytes, including all other data to be recorded in APP1.
	JPEGRestartInterval( 0x0203, FieldType.Short ), // This Field indicates the length of the restart interval used in the compressed image data.
	JPEGLosslessPredictors( 0x0205, FieldType.Short ), // This Field points to a list of lossless predictor-selection values, one per component.
	JPEGPointTransforms( 0x0206, FieldType.Short ), // This Field points to a list of point transform values, one per component.
	JPEGQTables( 0x0207, FieldType.Long ), // This Field points to a list of offsets to the quantization tables, one per component.
	JPEGDCTables( 0x0208, FieldType.Long ), // This Field points to a list of offsets to the DC Huffman tables or the lossless Huffman tables, one per component.
	JPEGACTables( 0x0209, FieldType.Long ), // This Field points to a list of offsets to the Huffman AC tables, one per component.
	YCbCrCoefficients( 0x0211, FieldType.Rational ), // The matrix coefficients for transformation from RGB to YCbCr image data. No default is given in TIFF; but here the value given in Appendix E, &#34;Color Space Guidelines&#34;, is used as the default. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability this condition.
	YCbCrSubSampling( 0x0212, FieldType.Short ), // The sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag.
	YCbCrPositioning( 0x0213, FieldType.Short ), // The position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data. The TIFF default is 1 (centered); but when Y:Cb:Cr = 4:2:2 it is recommended in this standard that 2 (co-sited) be used to record data, in order to improve the image quality when viewed on TV systems. When this field does not exist, the reader shall assume the TIFF default. In the case of Y:Cb:Cr = 4:2:0, the TIFF default (centered) is recommended. If the reader does not have the capability of supporting both kinds of &lt;YCbCrPositioning&gt;, it shall follow the TIFF default regardless of the value in this field. It is preferable that readers be able to support both centered and co-sited positioning.
	ReferenceBlackWhite( 0x0214, FieldType.Rational ), // The reference black point value and reference white point value. No defaults are given in TIFF, but the values below are given as defaults here. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions.
	XMLPacket( 0x02bc, FieldType.Byte ), // XMP Metadata (Adobe technote 9-14-02)
	Rating( 0x4746, FieldType.Short ), // Rating tag used by Windows
	RatingPercent( 0x4749, FieldType.Short ), // Rating tag used by Windows, value in percent
	ImageID( 0x800d, FieldType.Ascii ), // ImageID is the full pathname of the original, high-resolution image, or any other identifying string that uniquely identifies the original image (Adobe OPI).
	CFARepeatPatternDim( 0x828d, FieldType.Short ), // Contains two values representing the minimum rows and columns to define the repeating patterns of the color filter array
	CFAPattern( 0x828e, FieldType.Byte ), // Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods
	BatteryLevel( 0x828f, FieldType.Rational ), // Contains a value of the battery level as a fraction or string
	Copyright( 0x8298, FieldType.Ascii ), // Copyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image. The Interoperability copyright statement including date and rights should be written in this field; e.g., &#34;Copyright, John Smith, 19xx. All rights reserved.&#34;. In this standard the field records both the photographer and editor copyrights, with each recorded in a separate part of the statement. When there is a clear distinction between the photographer and editor copyrights, these are to be written in the order of photographer followed by editor copyright, separated by NULL (in this case since the statement also ends with a NULL, there are two NULL codes). When only the photographer copyright is given, it is terminated by one NULL code. When only the editor copyright is given, the photographer copyright part consists of one space followed by a terminating NULL code, then the editor copyright is given. When the field is left blank, it is treated as unknown.
	ExposureTime( 0x829a, FieldType.Rational ), // Exposure time, given in seconds.
	FNumber( 0x829d, FieldType.Rational ), // The F number.
	IPTCNAA( 0x83bb, FieldType.Long ), // Contains an IPTC/NAA record
	ImageResources( 0x8649, FieldType.Byte ), // Contains information embedded by the Adobe Photoshop application
	ExifTag( 0x8769, FieldType.Long ), // A pointer to the Exif IFD. Interoperability, Exif IFD has the same structure as that of the IFD specified in TIFF. ordinarily, however, it does not contain image data as in the case of TIFF.
	InterColorProfile( 0x8773, FieldType.Undefined ), // Contains an InterColor Consortium (ICC) format color space characterization/profile
	ExposureProgram( 0x8822, FieldType.Short ), // The class of the program used by the camera to set exposure when the picture is taken.
	SpectralSensitivity( 0x8824, FieldType.Ascii ), // Indicates the spectral sensitivity of each channel of the camera used.
	GPSTag( 0x8825, FieldType.Long ), // A pointer to the GPS Info IFD. The Interoperability structure of the GPS Info IFD, like that of Exif IFD, has no image data.
	ISOSpeedRatings( 0x8827, FieldType.Short ), // Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.
	OECF( 0x8828, FieldType.Undefined ), // Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.
	Interlace( 0x8829, FieldType.Short ), // Indicates the field number of multifield images.
	TimeZoneOffset( 0x882a, FieldType.SShort ), // This optional tag encodes the time zone of the camera clock (relative to Greenwich Mean Time) used to create the DataTimeOriginal tag-value when the picture was taken. It may also contain the time zone offset of the clock used to create the DateTime tag-value when the image was modified.
	SelfTimerMode( 0x882b, FieldType.Short ), // Number of seconds image capture was delayed from button press.
	DateTimeOriginal( 0x9003, FieldType.Ascii ), // The date and time when the original image data was generated.
	CompressedBitsPerPixel( 0x9102, FieldType.Rational ), // Specific to compressed data; states the compressed bits per pixel.
	ShutterSpeedValue( 0x9201, FieldType.SRational ), // Shutter speed.
	ApertureValue( 0x9202, FieldType.Rational ), // The lens aperture.
	BrightnessValue( 0x9203, FieldType.SRational ), // The value of brightness.
	ExposureBiasValue( 0x9204, FieldType.SRational ), // The exposure bias.
	MaxApertureValue( 0x9205, FieldType.Rational ), // The smallest F number of the lens.
	SubjectDistance( 0x9206, FieldType.SRational ), // The distance to the subject, given in meters.
	MeteringMode( 0x9207, FieldType.Short ), // The metering mode.
	LightSource( 0x9208, FieldType.Short ), // The kind of light source.
	Flash( 0x9209, FieldType.Short ), // Indicates the status of flash when the image was shot.
	FocalLength( 0x920a, FieldType.Rational ), // The actual focal length of the lens, in mm.
	FlashEnergy( 0x920b, FieldType.Rational ), // Amount of flash energy (BCPS).
	SpatialFrequencyResponse( 0x920c, FieldType.Undefined ), // SFR of the camera.
	Noise( 0x920d, FieldType.Undefined ), // Noise measurement values.
	FocalPlaneXResolution( 0x920e, FieldType.Rational ), // Number of pixels per FocalPlaneResolutionUnit (37392) in ImageWidth direction for main image.
	FocalPlaneYResolution( 0x920f, FieldType.Rational ), // Number of pixels per FocalPlaneResolutionUnit (37392) in ImageLength direction for main image.
	FocalPlaneResolutionUnit( 0x9210, FieldType.Short ), // Unit of measurement for FocalPlaneXResolution(37390) and FocalPlaneYResolution(37391).
	ImageNumber( 0x9211, FieldType.Long ), // Number assigned to an image, e.g., in a chained image burst.
	SecurityClassification( 0x9212, FieldType.Ascii ), // Security classification assigned to the image.
	ImageHistory( 0x9213, FieldType.Ascii ), // Record of what has been done to the image.
	SubjectLocation( 0x9214, FieldType.Short ), // Indicates the location and area of the main subject in the overall scene.
	ExposureIndex( 0x9215, FieldType.Rational ), // Encodes the camera exposure index setting when image was captured.
	TIFFEPStandardID( 0x9216, FieldType.Byte ), // Contains four ASCII characters representing the TIFF/EP standard version of a TIFF/EP file, eg &#39;1&#39;, &#39;0&#39;, &#39;0&#39;, &#39;0&#39;
	SensingMethod( 0x9217, FieldType.Short ), // Type of image sensor.
	XPTitle( 0x9c9b, FieldType.Byte ), // Title tag used by Windows, encoded in UCS2
	XPComment( 0x9c9c, FieldType.Byte ), // Comment tag used by Windows, encoded in UCS2
	XPAuthor( 0x9c9d, FieldType.Byte ), // Author tag used by Windows, encoded in UCS2
	XPKeywords( 0x9c9e, FieldType.Byte ), // Keywords tag used by Windows, encoded in UCS2
	XPSubject( 0x9c9f, FieldType.Byte ), // Subject tag used by Windows, encoded in UCS2
	PrintImageMatching( 0xc4a5, FieldType.Undefined ), // Print Image Matching, description needed.
	DNGVersion( 0xc612, FieldType.Byte ), // This tag encodes the DNG four-tier version number. For files compliant with version 1.1.0.0 of the DNG specification, this tag should contain the bytes: 1, 1, 0, 0.
	DNGBackwardVersion( 0xc613, FieldType.Byte ), // This tag specifies the oldest version of the Digital Negative specification for which a file is compatible. Readers shouldnot attempt to read a file if this tag specifies a version number that is higher than the version number of the specification the reader was based on.  In addition to checking the version tags, readers should, for all tags, check the types, counts, and values, to verify it is able to correctly read the file.
	UniqueCameraModel( 0xc614, FieldType.Ascii ), // Defines a unique, non-localized name for the camera model that created the image in the raw file. This name should include the manufacturer&#39;s name to avoid conflicts, and should not be localized, even if the camera name itself is localized for different markets (see LocalizedCameraModel). This string may be used by reader software to index into per-model preferences and replacement profiles.
	LocalizedCameraModel( 0xc615, FieldType.Byte ), // Similar to the UniqueCameraModel field, except the name can be localized for different markets to match the localization of the camera name.
	CFAPlaneColor( 0xc616, FieldType.Byte ), // Provides a mapping between the values in the CFAPattern tag and the plane numbers in LinearRaw space. This is a required tag for non-RGB CFA images.
	CFALayout( 0xc617, FieldType.Short ), // Describes the spatial layout of the CFA.
	LinearizationTable( 0xc618, FieldType.Short ), // Describes a lookup table that maps stored values into linear values. This tag is typically used to increase compression ratios by storing the raw data in a non-linear, more visually uniform space with fewer total encoding levels. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.
	BlackLevelRepeatDim( 0xc619, FieldType.Short ), // Specifies repeat pattern size for the BlackLevel tag.
	BlackLevel( 0xc61a, FieldType.Rational ), // Specifies the zero light (a.k.a. thermal black or black current) encoding level, as a repeating pattern. The origin of this pattern is the top-left corner of the ActiveArea rectangle. The values are stored in row-column-sample scan order.
	BlackLevelDeltaH( 0xc61b, FieldType.SRational ), // If the zero light encoding level is a function of the image column, BlackLevelDeltaH specifies the difference between the zero light encoding level for each column and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.
	BlackLevelDeltaV( 0xc61c, FieldType.SRational ), // If the zero light encoding level is a function of the image row, this tag specifies the difference between the zero light encoding level for each row and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel.
	WhiteLevel( 0xc61d, FieldType.Short ), // This tag specifies the fully saturated encoding level for the raw sample values. Saturation is caused either by the sensor itself becoming highly non-linear in response, or by the camera&#39;s analog to digital converter clipping.
	DefaultScale( 0xc61e, FieldType.Rational ), // DefaultScale is required for cameras with non-square pixels. It specifies the default scale factors for each direction to convert the image to square pixels. Typically these factors are selected to approximately preserve total pixel count. For CFA images that use CFALayout equal to 2, 3, 4, or 5, such as the Fujifilm SuperCCD, these two values should usually differ by a factor of 2.0.
	DefaultCropOrigin( 0xc61f, FieldType.Short ), // Raw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropOrigin specifies the origin of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied), relative to the top-left corner of the ActiveArea rectangle.
	DefaultCropSize( 0xc620, FieldType.Short ), // Raw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropSize specifies the size of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied).
	ColorMatrix1( 0xc621, FieldType.SRational ), // ColorMatrix1 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the first calibration illuminant. The matrix values are stored in row scan order. The ColorMatrix1 tag is required for all non-monochrome DNG files.
	ColorMatrix2( 0xc622, FieldType.SRational ), // ColorMatrix2 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the second calibration illuminant. The matrix values are stored in row scan order.
	CameraCalibration1( 0xc623, FieldType.SRational ), // CameraCalibration1 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the first calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix1 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer.
	CameraCalibration2( 0xc624, FieldType.SRational ), // CameraCalibration2 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the second calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix2 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer.
	ReductionMatrix1( 0xc625, FieldType.SRational ), // ReductionMatrix1 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the first calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order.
	ReductionMatrix2( 0xc626, FieldType.SRational ), // ReductionMatrix2 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the second calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order.
	AnalogBalance( 0xc627, FieldType.Rational ), // Normally the stored raw values are not white balanced, since any digital white balancing will reduce the dynamic range of the final image if the user decides to later adjust the white balance; however, if camera hardware is capable of white balancing the color channels before the signal is digitized, it can improve the dynamic range of the final image. AnalogBalance defines the gain, either analog (recommended) or digital (not recommended) that has been applied the stored raw values.
	AsShotNeutral( 0xc628, FieldType.Short ), // Specifies the selected white balance at time of capture, encoded as the coordinates of a perfectly neutral color in linear reference space values. The inclusion of this tag precludes the inclusion of the AsShotWhiteXY tag.
	AsShotWhiteXY( 0xc629, FieldType.Rational ), // Specifies the selected white balance at time of capture, encoded as x-y chromaticity coordinates. The inclusion of this tag precludes the inclusion of the AsShotNeutral tag.
	BaselineExposure( 0xc62a, FieldType.SRational ), // Camera models vary in the trade-off they make between highlight headroom and shadow noise. Some leave a significant amount of highlight headroom during a normal exposure. This allows significant negative exposure compensation to be applied during raw conversion, but also means normal exposures will contain more shadow noise. Other models leave less headroom during normal exposures. This allows for less negative exposure compensation, but results in lower shadow noise for normal exposures. Because of these differences, a raw converter needs to vary the zero point of its exposure compensation control from model to model. BaselineExposure specifies by how much (in EV units) to move the zero point. Positive values result in brighter default results, while negative values result in darker default results.
	BaselineNoise( 0xc62b, FieldType.Rational ), // Specifies the relative noise level of the camera model at a baseline ISO value of 100, compared to a reference camera model. Since noise levels tend to vary approximately with the square root of the ISO value, a raw converter can use this value, combined with the current ISO, to estimate the relative noise level of the current image.
	BaselineSharpness( 0xc62c, FieldType.Rational ), // Specifies the relative amount of sharpening required for this camera model, compared to a reference camera model. Camera models vary in the strengths of their anti-aliasing filters. Cameras with weak or no filters require less sharpening than cameras with strong anti-aliasing filters.
	BayerGreenSplit( 0xc62d, FieldType.Long ), // Only applies to CFA images using a Bayer pattern filter array. This tag specifies, in arbitrary units, how closely the values of the green pixels in the blue/green rows track the values of the green pixels in the red/green rows. A value of zero means the two kinds of green pixels track closely, while a non-zero value means they sometimes diverge. The useful range for this tag is from 0 (no divergence) to about 5000 (quite large divergence).
	LinearResponseLimit( 0xc62e, FieldType.Rational ), // Some sensors have an unpredictable non-linearity in their response as they near the upper limit of their encoding range. This non-linearity results in color shifts in the highlight areas of the resulting image unless the raw converter compensates for this effect. LinearResponseLimit specifies the fraction of the encoding range above which the response may become significantly non-linear.
	CameraSerialNumber( 0xc62f, FieldType.Ascii ), // CameraSerialNumber contains the serial number of the camera or camera body that captured the image.
	LensInfo( 0xc630, FieldType.Rational ), // Contains information about the lens that captured the image. If the minimum f-stops are unknown, they should be encoded as 0/0.
	ChromaBlurRadius( 0xc631, FieldType.Rational ), // ChromaBlurRadius provides a hint to the DNG reader about how much chroma blur should be applied to the image. If this tag is omitted, the reader will use its default amount of chroma blurring. Normally this tag is only included for non-CFA images, since the amount of chroma blur required for mosaic images is highly dependent on the de-mosaic algorithm, in which case the DNG reader&#39;s default value is likely optimized for its particular de-mosaic algorithm.
	AntiAliasStrength( 0xc632, FieldType.Rational ), // Provides a hint to the DNG reader about how strong the camera&#39;s anti-alias filter is. A value of 0.0 means no anti-alias filter (i.e., the camera is prone to aliasing artifacts with some subjects), while a value of 1.0 means a strong anti-alias filter (i.e., the camera almost never has aliasing artifacts).
	ShadowScale( 0xc633, FieldType.SRational ), // This tag is used by Adobe Camera Raw to control the sensitivity of its &#39;Shadows&#39; slider.
	DNGPrivateData( 0xc634, FieldType.Byte ), // Provides a way for camera manufacturers to store private data in the DNG file for use by their own raw converters, and to have that data preserved by programs that edit DNG files.
	MakerNoteSafety( 0xc635, FieldType.Short ), // MakerNoteSafety lets the DNG reader know whether the EXIF MakerNote tag is safe to preserve along with the rest of the EXIF data. File browsers and other image management software processing an image with a preserved MakerNote should be aware that any thumbnail image embedded in the MakerNote may be stale, and may not reflect the current state of the full size image.
	CalibrationIlluminant1( 0xc65a, FieldType.Short ), // The illuminant used for the first set of color calibration tags (ColorMatrix1, CameraCalibration1, ReductionMatrix1). The legal values for this tag are the same as the legal values for the LightSource EXIF tag.
	CalibrationIlluminant2( 0xc65b, FieldType.Short ), // The illuminant used for an optional second set of color calibration tags (ColorMatrix2, CameraCalibration2, ReductionMatrix2). The legal values for this tag are the same as the legal values for the CalibrationIlluminant1 tag; however, if both are included, neither is allowed to have a value of 0 (unknown).
	BestQualityScale( 0xc65c, FieldType.Rational ), // For some cameras, the best possible image quality is not achieved by preserving the total pixel count during conversion. For example, Fujifilm SuperCCD images have maximum detail when their total pixel count is doubled. This tag specifies the amount by which the values of the DefaultScale tag need to be multiplied to achieve the best quality image size.
	RawDataUniqueID( 0xc65d, FieldType.Byte ), // This tag contains a 16-byte unique identifier for the raw image data in the DNG file. DNG readers can use this tag to recognize a particular raw image, even if the file&#39;s name or the metadata contained in the file has been changed. If a DNG writer creates such an identifier, it should do so using an algorithm that will ensure that it is very unlikely two different images will end up having the same identifier.
	OriginalRawFileName( 0xc68b, FieldType.Byte ), // If the DNG file was converted from a non-DNG raw file, then this tag contains the file name of that original raw file.
	OriginalRawFileData( 0xc68c, FieldType.Undefined ), // If the DNG file was converted from a non-DNG raw file, then this tag contains the compressed contents of that original raw file. The contents of this tag always use the big-endian byte order. The tag contains a sequence of data blocks. Future versions of the DNG specification may define additional data blocks, so DNG readers should ignore extra bytes when parsing this tag. DNG readers should also detect the case where data blocks are missing from the end of the sequence, and should assume a default value for all the missing blocks. There are no padding or alignment bytes between data blocks.
	ActiveArea( 0xc68d, FieldType.Short ), // This rectangle defines the active (non-masked) pixels of the sensor. The order of the rectangle coordinates is: top, left, bottom, right.
	MaskedAreas( 0xc68e, FieldType.Short ), // This tag contains a list of non-overlapping rectangle coordinates of fully masked pixels, which can be optionally used by DNG readers to measure the black encoding level. The order of each rectangle&#39;s coordinates is: top, left, bottom, right. If the raw image data has already had its black encoding level subtracted, then this tag should not be used, since the masked pixels are no longer useful.
	AsShotICCProfile( 0xc68f, FieldType.Undefined ), // This tag contains an ICC profile that, in conjunction with the AsShotPreProfileMatrix tag, provides the camera manufacturer with a way to specify a default color rendering from camera color space coordinates (linear reference values) into the ICC profile connection space. The ICC profile connection space is an output referred colorimetric space, whereas the other color calibration tags in DNG specify a conversion into a scene referred colorimetric space. This means that the rendering in this profile should include any desired tone and gamut mapping needed to convert between scene referred values and output referred values.
	AsShotPreProfileMatrix( 0xc690, FieldType.SRational ), // This tag is used in conjunction with the AsShotICCProfile tag. It specifies a matrix that should be applied to the camera color space coordinates before processing the values through the ICC profile specified in the AsShotICCProfile tag. The matrix is stored in the row scan order. If ColorPlanes is greater than three, then this matrix can (but is not required to) reduce the dimensionality of the color data down to three components, in which case the AsShotICCProfile should have three rather than ColorPlanes input components.
	CurrentICCProfile( 0xc691, FieldType.Undefined ), // This tag is used in conjunction with the CurrentPreProfileMatrix tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers.
	CurrentPreProfileMatrix( 0xc692, FieldType.SRational ), // This tag is used in conjunction with the CurrentICCProfile tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers.
	ColorimetricReference( 0xc6bf, FieldType.Short ), // The DNG color model documents a transform between camera colors and CIE XYZ values. This tag describes the colorimetric reference for the CIE XYZ values. 0 = The XYZ values are scene-referred. 1 = The XYZ values are output-referred, using the ICC profile perceptual dynamic range. This tag allows output-referred data to be stored in DNG files and still processed correctly by DNG readers.
	CameraCalibrationSignature( 0xc6f3, FieldType.Byte ), // A UTF-8 encoded string associated with the CameraCalibration1 and CameraCalibration2 tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transform if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile.
	ProfileCalibrationSignature( 0xc6f4, FieldType.Byte ), // A UTF-8 encoded string associated with the camera profile tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transfer if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile.
	AsShotProfileName( 0xc6f6, FieldType.Byte ), // A UTF-8 encoded string containing the name of the &#34;as shot&#34; camera profile, if any.
	NoiseReductionApplied( 0xc6f7, FieldType.Rational ), // This tag indicates how much noise reduction has been applied to the raw data on a scale of 0.0 to 1.0. A 0.0 value indicates that no noise reduction has been applied. A 1.0 value indicates that the &#34;ideal&#34; amount of noise reduction has been applied, i.e. that the DNG reader should not apply additional noise reduction by default. A value of 0/0 indicates that this parameter is unknown.
	ProfileName( 0xc6f8, FieldType.Byte ), // A UTF-8 encoded string containing the name of the camera profile. This tag is optional if there is only a single camera profile stored in the file but is required for all camera profiles if there is more than one camera profile stored in the file.
	ProfileHueSatMapDims( 0xc6f9, FieldType.Long ), // This tag specifies the number of input samples in each dimension of the hue/saturation/value mapping tables. The data for these tables are stored in ProfileHueSatMapData1 and ProfileHueSatMapData2 tags. The most common case has ValueDivisions equal to 1, so only hue and saturation are used as inputs to the mapping table.
	ProfileHueSatMapData1( 0xc6fa, FieldType.Float ), // This tag contains the data for the first hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.
	ProfileHueSatMapData2( 0xc6fb, FieldType.Float ), // This tag contains the data for the second hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is a saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.
	ProfileToneCurve( 0xc6fc, FieldType.Float ), // This tag contains a default tone curve that can be applied while processing the image as a starting point for user adjustments. The curve is specified as a list of 32-bit IEEE floating-point value pairs in linear gamma. Each sample has an input value in the range of 0.0 to 1.0, and an output value in the range of 0.0 to 1.0. The first sample is required to be (0.0, 0.0), and the last sample is required to be (1.0, 1.0). Interpolated the curve using a cubic spline.
	ProfileEmbedPolicy( 0xc6fd, FieldType.Long ), // This tag contains information about the usage rules for the associated camera profile.
	ProfileCopyright( 0xc6fe, FieldType.Byte ), // A UTF-8 encoded string containing the copyright information for the camera profile. This string always should be preserved along with the other camera profile tags.
	ForwardMatrix1( 0xc714, FieldType.SRational ), // This tag defines a matrix that maps white balanced camera colors to XYZ D50 colors.
	ForwardMatrix2( 0xc715, FieldType.SRational ), // This tag defines a matrix that maps white balanced camera colors to XYZ D50 colors.
	PreviewApplicationName( 0xc716, FieldType.Byte ), // A UTF-8 encoded string containing the name of the application that created the preview stored in the IFD.
	PreviewApplicationVersion( 0xc717, FieldType.Byte ), // A UTF-8 encoded string containing the version number of the application that created the preview stored in the IFD.
	PreviewSettingsName( 0xc718, FieldType.Byte ), // A UTF-8 encoded string containing the name of the conversion settings (for example, snapshot name) used for the preview stored in the IFD.
	PreviewSettingsDigest( 0xc719, FieldType.Byte ), // A unique ID of the conversion settings (for example, MD5 digest) used to render the preview stored in the IFD.
	PreviewColorSpace( 0xc71a, FieldType.Long ), // This tag specifies the color space in which the rendered preview in this IFD is stored. The default value for this tag is sRGB for color previews and Gray Gamma 2.2 for monochrome previews.
	PreviewDateTime( 0xc71b, FieldType.Ascii ), // This tag is an ASCII string containing the name of the date/time at which the preview stored in the IFD was rendered. The date/time is encoded using ISO 8601 format.
	RawImageDigest( 0xc71c, FieldType.Undefined ), // This tag is an MD5 digest of the raw image data. All pixels in the image are processed in row-scan order. Each pixel is zero padded to 16 or 32 bits deep (16-bit for data less than or equal to 16 bits deep, 32-bit otherwise). The data for each pixel is processed in little-endian byte order.
	OriginalRawFileDigest( 0xc71d, FieldType.Undefined ), // This tag is an MD5 digest of the data stored in the OriginalRawFileData tag.
	SubTileBlockSize( 0xc71e, FieldType.Long ), // Normally, the pixels within a tile are stored in simple row-scan order. This tag specifies that the pixels within a tile should be grouped first into rectangular blocks of the specified size. These blocks are stored in row-scan order. Within each block, the pixels are stored in row-scan order. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0.
	RowInterleaveFactor( 0xc71f, FieldType.Long ), // This tag specifies that rows of the image are stored in interleaved order. The value of the tag specifies the number of interleaved fields. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0.
	ProfileLookTableDims( 0xc725, FieldType.Long ), // This tag specifies the number of input samples in each dimension of a default &#34;look&#34; table. The data for this table is stored in the ProfileLookTableData tag.
	ProfileLookTableData( 0xc726, FieldType.Float ), // This tag contains a default &#34;look&#34; table that can be applied while processing the image as a starting point for user adjustment. This table uses the same format as the tables stored in the ProfileHueSatMapData1 and ProfileHueSatMapData2 tags, and is applied in the same color space. However, it should be applied later in the processing pipe, after any exposure compensation and/or fill light stages, but before any tone curve stage. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees, the second entry is a saturation scale factor, and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0.
	OpcodeList1( 0xc740, FieldType.Undefined ), // Specifies the list of opcodes that should be applied to the raw image, as read directly from the file.
	OpcodeList2( 0xc741, FieldType.Undefined ), // Specifies the list of opcodes that should be applied to the raw image, just after it has been mapped to linear reference values.
	OpcodeList3( 0xc74e, FieldType.Undefined ), // Specifies the list of opcodes that should be applied to the raw image, just after it has been demosaiced.
	NoiseProfile( 0xc761, FieldType.Double ), // NoiseProfile describes the amount of noise in a raw image. Specifically, this tag models the amount of signal-dependent photon (shot) noise and signal-independent sensor readout noise, two common sources of noise in raw images. The model assumes that the noise is white and spatially independent, ignoring fixed pattern effects and other sources of noise (e.g., pixel response non-uniformity, spatially-dependent thermal effects, etc.).
	TimeCodes( 0xc763, FieldType.Byte ), // The optional TimeCodes tag shall contain an ordered array of time codes. All time codes shall be 8 bytes long and in binary format. The tag may contain from 1 to 10 time codes. When the tag contains more than one time code, the first one shall be the default time code. This specification does not prescribe how to use multiple time codes. Each time code shall be as defined for the 8-byte time code structure in SMPTE 331M-2004, Section 8.3. See also SMPTE 12-1-2008 and SMPTE 309-1999.
	FrameRate( 0xc764, FieldType.SRational ), // The optional FrameRate tag shall specify the video frame rate in number of image frames per second, expressed as a signed rational number. The numerator shall be non-negative and the denominator shall be positive. This field value is identical to the sample rate field in SMPTE 377-1-2009.
	TStop( 0xc772, FieldType.SRational ), // The optional TStop tag shall specify the T-stop of the actual lens, expressed as an unsigned rational number. T-stop is also known as T-number or the photometric aperture of the lens. (F-number is the geometric aperture of the lens.) When the exact value is known, the T-stop shall be specified using a single number. Alternately, two numbers shall be used to indicate a T-stop range, in which case the first number shall be the minimum T-stop and the second number shall be the maximum T-stop.
	ReelName( 0xc789, FieldType.Ascii ), // The optional ReelName tag shall specify a name for a sequence of images, where each image in the sequence has a unique image identifier (including but not limited to file name, frame number, date time, time code).
	CameraLabel( 0xc7a1, FieldType.Ascii ), // The optional CameraLabel tag shall specify a text label for how the camera is used or assigned in this clip. This tag is similar to CameraLabel in XMP.
	;

	private final ExifTagReference reference;

	Image( final int id, final FieldType type ) {
		this.reference = new ExifTagReference( id, ImageFileDirectory.Image, type );
	}

	@Override
	public ExifTagReference get() {
		return reference;
	}
}
