dist: trusty
language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

env:
  global:
    - secure: "QLDxPHbrSZNb1FyUeCNfJCxmBGcyMFPxhx0Gjco/N9H5c9SYauJfSu+/LdTbKxjP7JoA+GWYsCfzjn/QH0rz5hbcFVLI1E9vqUmtE3skLQT012JoeZALryRQKKqPt7ltGkoh4Ri+HTZmLl9q8blnGtAjfGsLf9muIqgBw16tbT0KQHSUmEgc2ulmyim35nO/zWKfVJdHJfSGkmerwuAHYzbWeerSQAr5FCyON4Bi+Wca/ZiswWZI4jULTlHQ4WWu+zn6Ofruh48//udMYgpO379X2IpRxtJa5/P7wxCzlJepibwp4/lHSsHIEjHk8SkAJvwr03bS7YGcz4BEoonflobFmC5QULcL6KfZUoETdh1X8eMNU198n792+udOoQj6TkbZEYGZm6p5XKriSK3UbQloU76SFx0PmkdKZvQj0fAcHxJDIUesVkB1zUNxjRB7feS5rvGw1et/jtlHRXbg1PR3JWaxqnxCXyWVfF98z8AEbt/UsuTcftrKCvaEy/d9CbcmBHPPLFZKCTr5gtthPfbLHdcsI+y11K5x48DXW74vkdIefsdGWFFiNSNq2VY6ecF+9GN6diw8cxo6LnWyTGcLpQ/RDf3jll1MgDyZjpt/ki2ZdH34aIXvFsoT8rdtoBFt2zZ50O3yaS46nMi+S4X6xXxSPKi7XZyIrkoCE9g="
    - secure: "oBGoZgVQF6yy3t9uqRgP9o2yOvQZj2jxZ38tfLIyNPqLJ0IWyS9dZXbh7GYuqudD+ps6GtC9zHDhWP1OvYsauvcpqRlf/8fhGJIsX/cJ95BbNGMmFzfVSXnB3h2W4tCXcx2vJAvsyJHIyULDXFuMTPGhiP2+ewaS0/mNDCjRHwDzOvRM59j+t9kb0v+bOHg29fA9F1rDFb5lqGziCg9uCJjFIp/OT9qZNIPYb+n5V68kSowULv9RadWK+c9UI4hBKGclj7jfu+2HIA2/Jlw3pcaajFT3GluClyQ8JdUZVwtwupDhcL02jig1PF0ud9LyViyHcT4ETwLvGwKVToXOAf56jJMdqZlRXsi5HMZDjHR11RKcdu/LRJAdF/Y7ZrVo3es8MbNnlZVM6jkhBsNArnN+7Z9n1IlfZ2xicBj7Qq2+d6jUAHYM6NNty4snMSbQCdb3SLUAXy7bRdGxBycZpNenBNBHrtkkEKOSP526smWLfW02fz8jQmwkLFWbVdvvNiPAP4FTndjreKum7ITrWYst3QG2aprJDWGx8CIKBZLST+HVbUe7Xi0wNMYHsmmGonImyPXEyq5Ikebgx4SM7gymRqUgafOsZTR/aS0y2PKuXnFG4b3A4p+6R/LFgTVneggmQ59gBcsM+pv/nQI6y8ugVzxOm9EOiiIVxPndiLI="

after_success:
  - mvn clean deploy --settings settings.xml
